### PR TITLE
Gracefully handle query not being a vector

### PR DESCRIPTION
**Pull request by miikka**
To solve issue #8. I haven't really coded Go, so not sure if this is a good solution.

### CODE REVIEW

**Comment by lispyclouds** [comment]
I can take a look at it today.

**Comment by borkdude** [comment]
@miikka Wow, awesome that you took a stab at this. Can you make one more dummy commit? CircleCI wasn't setup to build forked pull requests.

**Comment by lispyclouds** [comment]
@borkdude whats your opinion of allowing this behaviour? If its called with a string we take it as an unparameterized SQL query? We can check this on the Go side.

**Comment by borkdude** [comment]
@lispyclouds I was also thinking about this, but maybe it's better to stick with the behavior that people are used to from clojure.java.jdbc / next.jdbc?

**Comment by lispyclouds** [comment]
yeah we can support both too, my rationale being since this a scripting env, a lot of people could simply pass along a string? but I'm fine keeping this behaviour too.

**Comment by borkdude** [comment]
OK, yolo, let's do it.

**Comment by lispyclouds** [comment]
I'll have a go at adding more commits to this PR over the day.

**Comment by borkdude** [comment]
@lispyclouds If we're going to release a new version of this pod, we might also want to upgrade some deps, it's been a year.

**Comment by lispyclouds** [comment]
Right, will do that too. Maybe some Go 1.18 goodness too? 😛

**Comment by borkdude** [comment]
Whatever you fancy! :)

**Comment by lispyclouds** [comment]
I guess the PR doesnt allow edits from maintainers? Im pushing to another branch with this commits. Also not doing the go 1.18 stuff, needs different images and what not, it still being in beta

**Comment by lispyclouds** [comment]
Handled in https://github.com/babashka/pod-babashka-go-sqlite3/pull/10

**Pull request closed without merging**
