### PR TITLE
Update go-sqlite3 to 1.14.22

### PR DESCRIPTION
**Pull request by eval**

### CODE REVIEW

**Comment by borkdude** [comment]
Not sure what's up with the Windows CI. What's the goal of this update, just out of curiosity?

**Comment by eval** [comment]
> Not sure what's up with the Windows CI
Build required go 1.19. Upgrading image and setup seemed to work.

> What's the goal of this update, just out of curiosity?

This [upgrades sqlite](https://github.com/mattn/go-sqlite3/compare/v1.14.16...v1.14.22#diff-7b152b4c2dd396e8aaf98367a72a62f9d771a5b9aed88aa505dda0ba66f5b782) from 3.39.4 (Sept '22) to 3.45.1 (Jan '24).

**Comment by borkdude** [comment]
My question is more about: why do you need this upgrade

**Comment by borkdude** [comment]
Thanks btw!

**Comment by eval** [comment]
> My question is more about: why do you need this upgrade

No particular reason - chain of events: json1 functions didn't work, thought this pod needed an upgrade, turned out I copy-pasted an old pod-version from the bb-book (hence that PR), already did the work so therefor this PR :)

Thanks for the merge!

**Pull request merged**
